<?php
include "aud_header.php";

//$op = $oms->select_operational();
$aud_name = $oms->select_auditor_name();
$viewintrL = $oms->view_intrL();
$Eid = $oms->select_engagement_id();
$audit_type = $oms->select_auditType();

$auditeeList = $oms->select_auditee();

if (isset($_POST['submit'])) {
    $savec = $oms->intrL($_POST);
}
if (isset($_POST['edit'])) {
    $editintrL = $oms->edit_intrL($_POST);
}
if (isset($_POST['delete'])) {

    $delintrL = $oms->del_intrL();
}
?>

<div id="page-wrapper">

    <div class="row">
        <div class="col-lg-10">
            <?php
            if (isset($savech['su'])) {
                echo $savech['su'];
            }
            ?>

            <h4 class="page-header">Introduction Letter</h4>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- <button type="button" class="btn btn-info" data-toggle="modal" data-target="#form_modal"><span class="glyphicon glyphicon-plus"></span> Add user</button> -->
    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#form_modal"><span class="glyphicon glyphicon-plus"></span>Add new Introduction Letter</button>

    <div class="row">
        <div class="col-sm-10">


        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">

                <div class="panel-heading">

                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">

                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>


                                <th>Enagagement ID</th>
                                <th>Date</th>
                                <th>Reference</th>
                                <th>Generated by:Team Leader</th>
                                <th>Chief Internal Auitor/ Team Leaders</th>
                                <th>Audit Type</th>
                                <th>Auditees</th>
                                <!-- <th>Auditors</th> -->
                                <th>Letter body</th>
                                <th>Operation</th>


                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($viewintrL) {
                                foreach ($viewintrL as $chValue) {
                            ?>
                                    <tr class="odd gradeX">
                                        <td><?php echo $chValue['E_id']; ?></td>
                                        <td><?php echo $chValue['date']; ?></td>
                                        <td><?php echo $chValue['reference']; ?></td>
                                        <td><?php echo $chValue['gene_by_tl']; ?></td>
                                        <td><?php echo $chValue['ch_tl']; ?></td>
                                        <td><?php echo $chValue['audit_type']; ?></td>
                                        <td><?php echo $chValue['auditee']; ?></td>

                                        <td><?php echo $chValue['detail']; ?></td>
                                        <td>
                                            <button type="submit" class="btn btn-info btn-sm editbtn1" data-toggle="modal" data-target="#editModal1<?php echo $chValue['id'] ?>"><span class="glyphicon glyphicon-edit"></span>Edit </button>
                                            <button type="submit" class="btn btn-danger btn-sm deletebtn " name="delete" value="Delete Data" data-toggle="modal" data-target="#deleteModal<?php echo $chValue['id'] ?>"><span class="glyphicon glyphicon-trash"></span></button>

                                        </td>
                                    </tr>
                                    <!-- ========Delete Modal======== -->
                                    <div class="modal modal-danger fade-in " id="deleteModal<?php echo $chValue['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h3 class="modal-title" id="exampleModalLabel">Delete Confirmation</h3>
                                                    <!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
                                                </div>
                                                <form role="form" method="POST" action="#">
                                                    <div class="modal-body">
                                                        <input type="hidden" name="id" id="id" value="<?php echo $chValue['id'] ?>">

                                                        <h4> Are You sure to delete this content!!</h4>

                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                                                        <button type="submit" name="delete" class="btn btn-danger" value="delete">Yes</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal fade" id="editModal1<?php echo $chValue['id'] ?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Update Introduction Letter</h5>
                                                    <div class="row">

                                                        <!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
                                                    </div>
                                                    <form role="form" method="POST" action="#">
                                                        <div class="modal-body">
                                                            <input type="hidden" name="up_id" id="up_id" value="<?php echo $chValue['id'] ?>">

                                                            <div class="form-group">
                                                                <label>Engagement ID</label>
                                                                <select name="E_id" class="form-control">
                                                                    <option value="">--- Select ---</option>
                                                                    <?php
                                                                    if (isset($Eid)) {
                                                                        foreach ($Eid as $value) {
                                                                    ?>
                                                                            <option value="<?php echo $value['id']; ?>"> <?php echo $value['id']; ?> </option>
                                                                    <?php }
                                                                    } ?>
                                                                </select>
                                                                <?php
                                                                if (isset($savec['E_id'])) {
                                                                    echo $savec['E_id'];
                                                                }
                                                                ?>
                                                            </div>
                                                            <div class="form-group">
                                                                <label>Date</label>
                                                                <input type="date" name="date" id="date" class="form-control" value="<?php echo $chValue['date'] ?>" placeholder="Enter Date">

                                                            </div>
                                                            <div class="form-group">
                                                                <label>Reference</label>
                                                                <input type="text" name="reference" id="reference" class="form-control" value="<?php echo $chValue['reference'] ?>" placeholder="Enter Reference">

                                                            </div>
                                                            <div class="form-group">
                                                                <label>Generated by Team Leader</label>
                                                                <input type="text" name="gene_by_tl" id="gene_by_tl" class="form-control" value="<?php echo $chValue['gene_by_tl'] ?>" placeholder="Generated by team leader">

                                                            </div>
                                                            <div class="form-group">
                                                                <label>Chief Internal Auditor/ Team Leader</label>
                                                                <input type="text" name="ch_tl" id="ch_tl" class="form-control" value="<?php echo $chValue['ch_tl'] ?>" placeholder="Chief Internal Auditor/ Team Leaders">

                                                            </div>
                                                            <div class=" form-group">
                                                                <label>Audit Type</label>
                                                                <input type="text" name="audit_type" id="audit_type" class="form-control" value="<?php echo $chValue['audit_type'] ?>" placeholder="Audit Type">

                                                            </div>
                                                            <div class=" form-group">
                                                                <label>Auditee</label>
                                                                <input type="text" name="auditee" id="auditee" class="form-control" value="<?php echo $chValue['auditee'] ?>" placeholder="Auditee">

                                                            </div>

                                                            <div class="form-group">
                                                                <label>Letter body</label>
                                                                <input type="text" name="detail" class="form-control" value="<?php echo $chValue['detail'] ?>" placeholder="detail">

                                                            </div>

                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                                            <button type="submit" name="edit" class="btn btn-info" value="edit">Update</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>

                                <?php
                                }
                            }
                                ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
    <!-- /.row -->
</div>



<!-- <div class="cliyerfix"></div> -->
<!-- /.row -->
</div>
<!-- /#page-wrapper -->
<div class="modal fade" id="form_modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="" enctype="multipart/form-data">
                <div class="modal-header">
                    <h3 class="modal-title">Adding Introduction Letter</h3>
                </div>

                <div class="modal-body">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">

                        <div class="form-group">
                            <label>Engagement ID</label>
                            <select name="E_id" class="form-control">
                                <option value="">--- Select ---</option>
                                <?php
                                if (isset($Eid)) {
                                    foreach ($Eid as $value) {
                                ?>
                                        <option value="<?php echo $value['id']; ?>"> <?php echo $value['id']; ?> </option>
                                <?php }
                                } ?>
                            </select>
                            <?php
                            if (isset($savec['E_id'])) {
                                echo $savec['E_id'];
                            }
                            ?>
                        </div>


                        <div class="form-group">
                            <label>Date</label>
                            <input type="date" name="date" class="form-control" value="<?php echo $chValue['date'] ?>" placeholder="Enter Date">

                        </div>
                        <!-- <div class="form-group">
                            <label>Reference</label>
                            <input type="text" name="reference" id="reference" class="form-control" value="<?php echo $chValue['reference'] ?>" placeholder="Enter Reference">

                        </div> -->
                        <div class="form-group">
                            <label>Reference</label>
                            <input type="text" name="reference" class="form-control" placeholder="Enter the refernce">

                        </div>
                        <!-- <div class="form-group">
                            <label>Generated by Team Leader</label>
                            <input type="text" name="gene_by_tl" id="gene_by_tl" class="form-control" value="<?php echo $chValue['gene_by_tl'] ?>" placeholder="Generated by team leader">

                        </div> -->
                        <div class="form-group">
                            <label>Auditor Name</label>
                            <select name="auditor_name" class="form-control">
                                <option value="">--- Select ---</option>
                                <?php
                                if (isset($aud_name)) {
                                    foreach ($aud_name as $value) {
                                ?>
                                        <option value="<?php echo $value['id']; ?>"> <?php echo $value['auditor_name']; ?> </option>
                                <?php }
                                } ?>
                            </select>
                            <?php
                            if (isset($savec['auditor_name'])) {
                                echo $savec['auditor_name'];
                            }
                            ?>
                        </div>
                        <!-- <div class="form-group">
                            <label>Chief Internal Auditor/ Team Leader</label>
                            <input type="text" name="ch_tl" id="ch_tl" class="form-control" value="<?php echo $chValue['ch_tl'] ?>" placeholder="Chief Internal Auditor/ Team Leaders">

                        </div> -->
                        <!-- <div class="form-group">
                            <label>Generated by:</label>
                            <input type="text" name="gene_by_tl" class="form-control" placeholder="Enter the Chief Internal Auditor/ Team Leader">

                        </div> -->
                        <div class="form-group">
                            <label>Generated by:</label>
                            <select name="auditor_name" class="form-control">
                                <option value="">--- Select ---</option>
                                <?php
                                if (isset($aud_name)) {
                                    foreach ($aud_name as $value) {
                                ?>
                                        <option value="<?php echo $value['id']; ?>"> <?php echo $value['auditor_name']; ?> </option>
                                <?php }
                                } ?>
                            </select>
                            <?php
                            if (isset($savec['auditor_name'])) {
                                echo $savec['auditor_name'];
                            }
                            ?>
                        </div>
                        <div class="form-group">
                            <label>Chief Internal Auditor/ Team Leader</label>
                            <input type="text" name="ch_tl" class="form-control" placeholder="Enter the Chief Internal Auditor/ Team Leader">

                        </div>
                        <!-- <div class=" form-group">
                            <label>Audit Type</label>
                            <input type="text" name="audit_type" id="audit_type" class="form-control" value="<?php echo $chValue['audit_type'] ?>" placeholder="Audit Type">

                        </div> -->
                        <div class="form-group">
                            <label>Audit Type</label>
                            <select name="audit_type" class="form-control">
                                <option value="">--- Select ---</option>
                                <?php
                                if (isset($audit_type)) {
                                    foreach ($audit_type as $value) {
                                ?>
                                        <option value="<?php echo $value['id']; ?>"> <?php echo $value['audit_type']; ?> </option>
                                <?php }
                                } ?>
                            </select>
                            <?php
                            if (isset($saveM['audit_type'])) {
                                echo $saveM['audit_type'];
                            }
                            ?>
                        </div>
                        <div class="form-group">
                            <label>Auditee</label>
                            <select name="auditee" class="form-control">
                                <option value="">--- Select ---</option>
                                <?php
                                if (isset($auditeeList)) {
                                    foreach ($auditeeList as $value) {
                                ?>
                                        <option value="<?php echo $value['id']; ?>"> <?php echo $value['auditee']; ?> </option>
                                <?php }
                                } ?>
                            </select>
                            <?php
                            if (isset($savec['auditee'])) {
                                echo $savec['auditee'];
                            }
                            ?>
                        </div>
                        <!-- <div class="form-group">
                            <label>Auditors List</label>
                            <input type="text" name="aud_list" id="aud_list" class="form-control" value="<?php echo $chValue['aud_list'] ?>" placeholder="Auditor List">

                        </div> -->

                        <!-- <div class="form-group">
                            <label>Letter body</label>
                            <input type="text" name="detail" id="detail" class="form-control" value="<?php echo $chValue['detail'] ?>" placeholder="detail">

                        </div> -->
                        <div class="form-group">
                            <label>Letter body</label>
                            <!-- <input type="text" name="detail" class="form-control" placeholder="Enter the Detail of Introduction Letter body"> -->
                            <textarea name="detail" type="text" class="form-control" id="editor5"></textarea>

                        </div>



                    </div>
                </div>
                <div style="clear:both;"></div>
                <div class="modal-footer">
                    <button type="submit" name="submit" class="btn btn-info" value="submit"><span class="glyphicon glyphicon-save"></span> Save</button>
                    <button class="btn btn-danger" type="button" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Close</button>
                </div>
        </div>
        </form>
    </div>
</div>


<?php
include "footer.php";
?>