<?php
include "tm_header.php";

$op = $oms->select_operational();
$viewintrL = $oms->view_intrL();
$aud_name = $oms->select_auditor_name();
$audit_type = $oms->select_auditType();
$E_id = $oms->select_engagement_id();
$auditee = $oms->select_auditee();

if (isset($_POST['submit'])) {
    $saveL = $oms->intrL($_POST);
}
if (isset($_POST['edit'])) {
    $editintrL = $oms->edit_intrL($_POST);
}
if (isset($_POST['delete'])) {

    $delintrL = $oms->del_intrL();
}
?>

<div id="page-wrapper">

    <div class="row">
        <div class="col-lg-10">
            <?php
            if (isset($savech['su'])) {
                echo $savech['su'];
            }
            ?>

            <h5 class="page-header">Introduction Letter</h5>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- <button type="button" class="btn btn-info" data-toggle="modal" data-target="#form_modal"><span class="glyphicon glyphicon-plus"></span> Add user</button> -->
    <!-- <button type="button" class="btn btn-info" data-toggle="modal" data-target="#form_modal"><span class="glyphicon glyphicon-plus"></span>Create Introduction Letter</button> -->
    <!-- <button type="button" class="btn btn-info" data-toggle="modal" data-target="#form_modal" href="http://desktop-ece92r2/Reports/Pages/Report.aspx?ItemPath=%2fuser%2fIntroduction+Letter" onclick="NewITab()"><i class="fa fa-reply-all"></i>&nbsp; Generate/Show Introduction Letter</button> -->
    <div class="row">
        <div class="col-sm-10">

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">

                <div class="panel-heading">

                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">

                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-eg1">
                        <thead>
                            <tr>



                                <th>Engagement ID</th>
                                <th>Date</th>
                                <th>Reference</th>
                                <!-- <th>Generated by:Team Leader</th> -->
                                <th>Chief Internal Auitor/ Team Leaders</th>
                                <!-- <th>Audit Type</th> -->
                                <th>Auditees</th>
                                <th>Auditors Name</th>
                                <th>Letter body</th>
                                <th>Operation</th>


                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($viewintrL) {
                                foreach ($viewintrL as $chValue) {
                            ?>
                                    <tr class="odd gradeX">
                                        <td><?php echo $chValue['E_id']; ?></td>
                                        <td><?php echo $chValue['date']; ?></td>
                                        <td><?php echo $chValue['reference']; ?></td>
                                        <td><?php echo $chValue['ch_tl']; ?></td>
                                        <td><?php echo $chValue['auditee']; ?></td>
                                        <td><?php echo $chValue['name']; ?></td>
                                        <td><?php echo $chValue['detail']; ?></td>
                                        <td>
                                            <button type="submit" class="btn btn-danger btn-sm deletebtn " name="delete" value="Delete Data" data-toggle="modal" data-target="#deleteModal<?php echo $chValue['id'] ?>"><span class="glyphicon glyphicon-trash"></span></button>

                                        </td>
                                    </tr>
                                    <!-- ========Delete Modal======== -->
                                    <div class="modal modal-danger fade-in " id="deleteModal<?php echo $chValue['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h3 class="modal-title" id="exampleModalLabel">Delete Confirmation</h3>
                                                    <!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
                                                </div>
                                                <form role="form" method="POST" action="#">
                                                    <div class="modal-body">
                                                        <input type="hidden" name="id" id="id" value="<?php echo $chValue['id'] ?>">

                                                        <h4> Are You sure to delete this content!!</h4>

                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                                                        <button type="submit" name="delete" class="btn btn-danger" value="delete">Yes</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal fade" id="editModal1<?php echo $chValue['id'] ?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title" id="exampleModalLabel">Update Introduction Letter</h4>
                                                    <div class="row">

                                                        <!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
                                                    </div>
                                                    <form role="form" method="POST" action="#">
                                                        <div class="modal-body">
                                                            <input type="hidden" name="up_id" id="up_id" value="<?php echo $chValue['id'] ?>">
                                                            <div class="form-group">
                                                                <label>Engagement ID</label>
                                                                <input type="text" name="E_id" id="E_id" class="form-control" value="<?php echo $chValue['E_id'] ?>" placeholder="Enter Engagement ID">
                                                            </div>
                                                            <div class="form-group">
                                                                <label>Date</label>
                                                                <input type="text" name="date" id="date" class="form-control" value="<?php echo $chValue['date'] ?>" placeholder="Enter date">
                                                            </div>
                                                            <div class="form-group">
                                                                <label>Reference</label>
                                                                <input type="text" name="reference" id="reference" class="form-control" value="<?php echo $chValue['reference'] ?>" placeholder="Enter Refernce">
                                                            </div>
                                                            <div class="form-group">
                                                                <label>Generated by Team Leader</label>
                                                                <input type="text" name="gene_by_tl" id="gene_by_tl" class="form-control" value="<?php echo $chValue['gene_by_tl'] ?>" placeholder="update team leader name ">
                                                            </div>
                                                            <div class="form-group">
                                                                <label>Chief Internal Auditor/ Team Leader</label>
                                                                <input type="text" name="ch_tl" id="ch_tl" class="form-control" value="<?php echo $chValue['ch_tl'] ?>" placeholder="cheif auditor">

                                                            </div>
                                                            <div class="form-group">
                                                                <label>Audit Type</label>
                                                                <input type="text" name="audit_type" id="audit_type" class="form-control" value="<?php echo $chValue['audit_type'] ?>" placeholder="Enter Audit Type">

                                                            </div>
                                                            <div class=" form-group">
                                                                <label>Auditee</label>
                                                                <input type="text" name="auditee" id="auditee" class="form-control" value="<?php echo $chValue['auditee'] ?>" placeholder="Auditee/Branches/Department">

                                                            </div>
                                                            <div class=" form-group">
                                                                <label>Auditors Name</label>
                                                                <input type="text" name="auditor_name" id="auditor_name" class="form-control" value="<?php echo $chValue['auditor_name'] ?>" placeholder="Auditor Names">

                                                            </div>

                                                            <div class=" form-group">
                                                                <label>Letter Body/Detail</label>
                                                                <input type="text" name="detail" id="detail" class="form-control" value="<?php echo $chValue['detail'] ?>" placeholder="update detail/ Body of letter">

                                                            </div>
                                                            <div class="form-group">
                                                                <label>Amend by:</label>
                                                                <input value="<?php echo Session::get("name"); ?>" class="form-control" disabled>

                                                            </div>
                                                        </div>
                                                        <div class="modal-footer">

                                                            <button type="submit" name="edit" class="btn btn-info" value="edit">Update</button>
                                                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>

                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>

                                <?php
                                }
                            }
                                ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
    <!-- /.row -->
</div>


<!-- <div class="cliyerfix"></div> -->
<!-- /.row -->
</div>
<!-- /#page-wrapper -->
<div class="modal fade" id="form_modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="#">
                <div class="modal-header">
                    <h3 class="modal-title">Introduction Letter</h3>
                </div>
                <div class="modal-body">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div class="form-group">
                            <label>Engagement ID</label>
                            <select name="E_id" class="form-control">
                                <option value="">--- Select ---</option>
                                <?php
                                if (isset($E_id)) {
                                    foreach ($E_id as $value) {
                                ?>
                                        <option value="<?php echo $value['id']; ?>"> <?php echo $value['id']; ?> </option>
                                <?php }
                                } ?>
                            </select>
                            <?php
                            if (isset($saveM['E_id'])) {
                                echo $saveM['E_id'];
                            }
                            ?>
                        </div>
                        <!-- <div class="form-group">
                            <label>Date</label>
                            <input type="date" name="date" class="form-control" placeholder="Enter Date">

                        </div> -->
                        <div class="form-group">
                            <label>Reference</label>
                            <input type="text" name="reference" class="form-control" placeholder="Enter reference">

                        </div>
                        <div class="form-group">
                            <label>Generated by Team Leader</label>
                            <input type="text" name="gene_by_tl" class="form-control" placeholder="Generated by Team Leader">

                        </div>
                        <div class="form-group">
                            <label>Chief Internal Auditor/ Team Leaders</label>
                            <input type="text" name="ch_tl" class="form-control" placeholder="Chief Internal Auditor/ Team Leaders">

                        </div>
                        <!-- <div class="form-group">
                            <label>Audit Type</label>
                            <input type="text" name="audit_type" class="form-control" placeholder="Audit Type">

                        </div> -->
                        <div class="form-group">
                            <label>Audit Type</label>
                            <select name="audit_type" class="form-control">
                                <option value="">--- Select ---</option>
                                <?php
                                if (isset($audit_type)) {
                                    foreach ($audit_type as $value) {
                                ?>
                                        <option value="<?php echo $value['audit_type']; ?>"> <?php echo $value['audit_type']; ?> </option>
                                <?php }
                                } ?>
                            </select>
                            <?php
                            if (isset($saveM['audit_type'])) {
                                echo $saveM['audit_type'];
                            }
                            ?>
                        </div>
                        <!-- <div class="form-group">
                            <label>Auditees</label>
                            <input type="text" name="auditee" class="form-control" placeholder="Auditees">

                        </div> -->
                        <div class="form-group">
                            <label>Auditee</label>
                            <select name="auditee" class="form-control">
                                <option value="">--- Select ---</option>
                                <?php
                                if (isset($auditee)) {
                                    foreach ($auditee as $value) {
                                ?>
                                        <option value="<?php echo $value['auditee']; ?>"> <?php echo $value['auditee']; ?> </option>
                                <?php }
                                } ?>
                            </select>
                            <?php
                            if (isset($saveM['auditee'])) {
                                echo $saveM['auditee'];
                            }
                            ?>
                        </div>

                        <div class="form-group">
                            <label>Auditor Name</label>
                            <select name="auditor_name" class="form-control">
                                <option value="">--- Select ---</option>
                                <?php
                                if (isset($aud_name)) {
                                    foreach ($aud_name as $value) {
                                ?>
                                        <option value="<?php echo $value['id']; ?>"> <?php echo $value['auditor_name']; ?> </option>
                                <?php }
                                } ?>
                            </select>
                            <?php
                            if (isset($savec['auditor_name'])) {
                                echo $savec['auditor_name'];
                            }
                            ?>
                        </div>
                        <div class="form-group">
                            <label>Letter Body</label>
                            <textarea name="detail" type="text" class="form-control" id="editorlb"></textarea>
                        </div>
                    </div>
                </div>
                <div style="clear:both;"></div>
                <div class="modal-footer">
                    <button type="submit" name="submit" class="btn btn-info" value="submit"><span class="glyphicon glyphicon-save"></span> Save</button>
                    <button class="btn btn-danger" type="button" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Close</button>
                </div>
        </div>
        </form>
    </div>
</div>

<?php
include "footer.php";
?>